// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: feed.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorKind int32

const (
	ErrorKind_ERROR_KIND_UNKNOWN       ErrorKind = 0
	ErrorKind_ERROR_KIND_SERIALIZATION ErrorKind = 1
	ErrorKind_ERROR_KIND_NETWORK       ErrorKind = 2
	ErrorKind_ERROR_KIND_PARSING       ErrorKind = 3
	ErrorKind_ERROR_KIND_VALIDATION    ErrorKind = 4
	ErrorKind_ERROR_KIND_INTERNAL      ErrorKind = 5
)

// Enum value maps for ErrorKind.
var (
	ErrorKind_name = map[int32]string{
		0: "ERROR_KIND_UNKNOWN",
		1: "ERROR_KIND_SERIALIZATION",
		2: "ERROR_KIND_NETWORK",
		3: "ERROR_KIND_PARSING",
		4: "ERROR_KIND_VALIDATION",
		5: "ERROR_KIND_INTERNAL",
	}
	ErrorKind_value = map[string]int32{
		"ERROR_KIND_UNKNOWN":       0,
		"ERROR_KIND_SERIALIZATION": 1,
		"ERROR_KIND_NETWORK":       2,
		"ERROR_KIND_PARSING":       3,
		"ERROR_KIND_VALIDATION":    4,
		"ERROR_KIND_INTERNAL":      5,
	}
)

func (x ErrorKind) Enum() *ErrorKind {
	p := new(ErrorKind)
	*p = x
	return p
}

func (x ErrorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_feed_proto_enumTypes[0].Descriptor()
}

func (ErrorKind) Type() protoreflect.EnumType {
	return &file_feed_proto_enumTypes[0]
}

func (x ErrorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorKind.Descriptor instead.
func (ErrorKind) EnumDescriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

type ParseFeedsStatus int32

const (
	ParseFeedsStatus_SUCCESS ParseFeedsStatus = 0
	ParseFeedsStatus_ERROR   ParseFeedsStatus = 1
	ParseFeedsStatus_PARTIAL ParseFeedsStatus = 2
)

// Enum value maps for ParseFeedsStatus.
var (
	ParseFeedsStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
		2: "PARTIAL",
	}
	ParseFeedsStatus_value = map[string]int32{
		"SUCCESS": 0,
		"ERROR":   1,
		"PARTIAL": 2,
	}
)

func (x ParseFeedsStatus) Enum() *ParseFeedsStatus {
	p := new(ParseFeedsStatus)
	*p = x
	return p
}

func (x ParseFeedsStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParseFeedsStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_feed_proto_enumTypes[1].Descriptor()
}

func (ParseFeedsStatus) Type() protoreflect.EnumType {
	return &file_feed_proto_enumTypes[1]
}

func (x ParseFeedsStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParseFeedsStatus.Descriptor instead.
func (ParseFeedsStatus) EnumDescriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{1}
}

type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ErrorKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=proto.ErrorKind" json:"kind,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetKind() ErrorKind {
	if x != nil {
		return x.Kind
	}
	return ErrorKind_ERROR_KIND_UNKNOWN
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetail) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ValidateFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateFeedRequest) Reset() {
	*x = ValidateFeedRequest{}
	mi := &file_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFeedRequest) ProtoMessage() {}

func (x *ValidateFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateFeedRequest.ProtoReflect.Descriptor instead.
func (*ValidateFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateFeedRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ValidateFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Error         *ErrorDetail           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateFeedResponse) Reset() {
	*x = ValidateFeedResponse{}
	mi := &file_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFeedResponse) ProtoMessage() {}

func (x *ValidateFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateFeedResponse.ProtoReflect.Descriptor instead.
func (*ValidateFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateFeedResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateFeedResponse) GetError() *ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ParseFeedsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseFeedsRequest) Reset() {
	*x = ParseFeedsRequest{}
	mi := &file_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseFeedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFeedsRequest) ProtoMessage() {}

func (x *ParseFeedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFeedsRequest.ProtoReflect.Descriptor instead.
func (*ParseFeedsRequest) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{3}
}

func (x *ParseFeedsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type ParseFeedsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ParseFeedsStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=proto.ParseFeedsStatus" json:"status,omitempty"`
	Feeds         []*Feed                `protobuf:"bytes,2,rep,name=feeds,proto3" json:"feeds,omitempty"`
	Errors        []*ErrorDetail         `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	FatalError    *ErrorDetail           `protobuf:"bytes,4,opt,name=fatal_error,json=fatalError,proto3" json:"fatal_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseFeedsResponse) Reset() {
	*x = ParseFeedsResponse{}
	mi := &file_feed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseFeedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseFeedsResponse) ProtoMessage() {}

func (x *ParseFeedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseFeedsResponse.ProtoReflect.Descriptor instead.
func (*ParseFeedsResponse) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{4}
}

func (x *ParseFeedsResponse) GetStatus() ParseFeedsStatus {
	if x != nil {
		return x.Status
	}
	return ParseFeedsStatus_SUCCESS
}

func (x *ParseFeedsResponse) GetFeeds() []*Feed {
	if x != nil {
		return x.Feeds
	}
	return nil
}

func (x *ParseFeedsResponse) GetErrors() []*ErrorDetail {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ParseFeedsResponse) GetFatalError() *ErrorDetail {
	if x != nil {
		return x.FatalError
	}
	return nil
}

type Feed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Image         *string                `protobuf:"bytes,5,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Items         []*FeedItem            `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Feed) Reset() {
	*x = Feed{}
	mi := &file_feed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Feed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feed) ProtoMessage() {}

func (x *Feed) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feed.ProtoReflect.Descriptor instead.
func (*Feed) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{5}
}

func (x *Feed) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Feed) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Feed) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Feed) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *Feed) GetItems() []*FeedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type FeedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Link          *string                `protobuf:"bytes,3,opt,name=link,proto3,oneof" json:"link,omitempty"`
	Image         *string                `protobuf:"bytes,4,opt,name=image,proto3,oneof" json:"image,omitempty"`
	Published     *string                `protobuf:"bytes,5,opt,name=published,proto3,oneof" json:"published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedItem) Reset() {
	*x = FeedItem{}
	mi := &file_feed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedItem) ProtoMessage() {}

func (x *FeedItem) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedItem.ProtoReflect.Descriptor instead.
func (*FeedItem) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{6}
}

func (x *FeedItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FeedItem) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *FeedItem) GetLink() string {
	if x != nil && x.Link != nil {
		return *x.Link
	}
	return ""
}

func (x *FeedItem) GetImage() string {
	if x != nil && x.Image != nil {
		return *x.Image
	}
	return ""
}

func (x *FeedItem) GetPublished() string {
	if x != nil && x.Published != nil {
		return *x.Published
	}
	return ""
}

var File_feed_proto protoreflect.FileDescriptor

const file_feed_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"feed.proto\x12\x05proto\"_\n" +
	"\vErrorDetail\x12$\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x10.proto.ErrorKindR\x04kind\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"'\n" +
	"\x13ValidateFeedRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"V\n" +
	"\x14ValidateFeedResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12(\n" +
	"\x05error\x18\x02 \x01(\v2\x12.proto.ErrorDetailR\x05error\"'\n" +
	"\x11ParseFeedsRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"\xc9\x01\n" +
	"\x12ParseFeedsResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.proto.ParseFeedsStatusR\x06status\x12!\n" +
	"\x05feeds\x18\x02 \x03(\v2\v.proto.FeedR\x05feeds\x12*\n" +
	"\x06errors\x18\x03 \x03(\v2\x12.proto.ErrorDetailR\x06errors\x123\n" +
	"\vfatal_error\x18\x04 \x01(\v2\x12.proto.ErrorDetailR\n" +
	"fatalError\"\xb1\x01\n" +
	"\x04Feed\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x05 \x01(\tH\x01R\x05image\x88\x01\x01\x12%\n" +
	"\x05items\x18\x06 \x03(\v2\x0f.proto.FeedItemR\x05itemsB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_image\"\xcf\x01\n" +
	"\bFeedItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x17\n" +
	"\x04link\x18\x03 \x01(\tH\x01R\x04link\x88\x01\x01\x12\x19\n" +
	"\x05image\x18\x04 \x01(\tH\x02R\x05image\x88\x01\x01\x12!\n" +
	"\tpublished\x18\x05 \x01(\tH\x03R\tpublished\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\a\n" +
	"\x05_linkB\b\n" +
	"\x06_imageB\f\n" +
	"\n" +
	"_published*\xa5\x01\n" +
	"\tErrorKind\x12\x16\n" +
	"\x12ERROR_KIND_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18ERROR_KIND_SERIALIZATION\x10\x01\x12\x16\n" +
	"\x12ERROR_KIND_NETWORK\x10\x02\x12\x16\n" +
	"\x12ERROR_KIND_PARSING\x10\x03\x12\x19\n" +
	"\x15ERROR_KIND_VALIDATION\x10\x04\x12\x17\n" +
	"\x13ERROR_KIND_INTERNAL\x10\x05*7\n" +
	"\x10ParseFeedsStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\v\n" +
	"\aPARTIAL\x10\x02B\"Z github.com/sunderee/rss-it/protob\x06proto3"

var (
	file_feed_proto_rawDescOnce sync.Once
	file_feed_proto_rawDescData []byte
)

func file_feed_proto_rawDescGZIP() []byte {
	file_feed_proto_rawDescOnce.Do(func() {
		file_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)))
	})
	return file_feed_proto_rawDescData
}

var file_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_feed_proto_goTypes = []any{
	(ErrorKind)(0),               // 0: proto.ErrorKind
	(ParseFeedsStatus)(0),        // 1: proto.ParseFeedsStatus
	(*ErrorDetail)(nil),          // 2: proto.ErrorDetail
	(*ValidateFeedRequest)(nil),  // 3: proto.ValidateFeedRequest
	(*ValidateFeedResponse)(nil), // 4: proto.ValidateFeedResponse
	(*ParseFeedsRequest)(nil),    // 5: proto.ParseFeedsRequest
	(*ParseFeedsResponse)(nil),   // 6: proto.ParseFeedsResponse
	(*Feed)(nil),                 // 7: proto.Feed
	(*FeedItem)(nil),             // 8: proto.FeedItem
}
var file_feed_proto_depIdxs = []int32{
	0, // 0: proto.ErrorDetail.kind:type_name -> proto.ErrorKind
	2, // 1: proto.ValidateFeedResponse.error:type_name -> proto.ErrorDetail
	1, // 2: proto.ParseFeedsResponse.status:type_name -> proto.ParseFeedsStatus
	7, // 3: proto.ParseFeedsResponse.feeds:type_name -> proto.Feed
	2, // 4: proto.ParseFeedsResponse.errors:type_name -> proto.ErrorDetail
	2, // 5: proto.ParseFeedsResponse.fatal_error:type_name -> proto.ErrorDetail
	8, // 6: proto.Feed.items:type_name -> proto.FeedItem
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_feed_proto_init() }
func file_feed_proto_init() {
	if File_feed_proto != nil {
		return
	}
	file_feed_proto_msgTypes[5].OneofWrappers = []any{}
	file_feed_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feed_proto_goTypes,
		DependencyIndexes: file_feed_proto_depIdxs,
		EnumInfos:         file_feed_proto_enumTypes,
		MessageInfos:      file_feed_proto_msgTypes,
	}.Build()
	File_feed_proto = out.File
	file_feed_proto_goTypes = nil
	file_feed_proto_depIdxs = nil
}
